# version format
version: "{build}"

skip_tags: false

clone_depth: 20

os: Visual Studio 2015

environment:

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.1"
      PYTHON_ARCH: "64"
      ARCH: x86_64
      VS_VER: "2015"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Should this be done here or via setup some how? it should not be part of the build/install requirements, just development
  - "pip install pytest"
 
  # Need cython first. TODO: pip install -e . should just work
  - "pip install cython"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - cd "%APPVEYOR_BUILD_FOLDER%\\emolog_pc"
  - python -c "import os; print(os.getcwd())"
  - "pip install -e .[pyinstaller]"

test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\\emolog_pc"
  - pytest --fulltrace --doctest-modules --junitxml=%APPVEYOR_BUILD_FOLDER\junit.xml tests
  # sanity of pyinstaller artifacts
  - 7z x  "%APPVEYOR_BUILD_FOLDER%\emolog_pc\dist\emotool.zip"
  - cd emotool
  - emotool.exe --help
  - emotool-vars.exe --help
  - emotool-dwarf.exe --help
  - emotool-dwarf-dump.exe --help 
  - cd %APPVEYOR_BUILD_FOLDER%\emolog_pc
  - emotool-dwarf-dump.exe -e tests\example.out
  - emotool-dwarf.exe -e tests\example.out -v tests\vars_example.csv
  - cd "%APPVEYOR_BUILD_FOLDER%\emolog_pc"
  - copy config\local_machine_config.ini.example local_machine_config.ini
  # TODO: full run of summarize, compare to known file
  # TODO: full run of emotool, compare to known result (include post_processing)
  - python misc\prof.py
  # sanity for the tools we have

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\\emolog_pc"
  - "python setup.py install"
  - cd "%APPVEYOR_BUILD_FOLDER%\\emolog_pc\\dist"
  # TODO: proper versions for both the zipped directory and the zip file
  # TODO -1: version reporting correctly for emotool
  - cd "%APPVEYOR_BUILD_FOLDER%\\emolog_pc"
  - "pyinstaller pyinstaller\\emotool.spec"
  - cd "%APPVEYOR_BUILD_FOLDER%\\emolog_pc\\dist"
  - 7z a emotool.zip emotool
  - dir %APPVEYOR_BUILD_FOLDER%
  - dir %APPVEYOR_BUILD_FOLDER%\emolog_pc\dist

artifacts:
  - path: emolog_pc\dist\emotool.zip
    name: emotool
